### ISSUE TITLE
Create test database

### ISSUE THREAD

**Issue by cthoyt** [bio2bel/chembl#14]
Obviously the entire ChEMBL sqlite dump can't be included in the repository, but it would be good to get a small sample of the relevant tables to include with the repository as test data.

Check the build info at: https://travis-ci.org/bio2bel/chembl/builds/264064303?utm_source=slack&utm_medium=notification

**Comment by aramgrigoryan** [comment]
it failed to download whole database? or coulndt open it due to limited resources?

**Comment by cthoyt** [comment]
Unit tests on travis can't be expected to operate on the 20gb file. Needs a smaller, representative sample with the same Schema
